Repository neocodejack/SalesAdminBurialPlots, pull requests merged in 2018-06, with the labels that each got.

#4 Develop
  SalesAdminPortal/SalesAdminPortal/Controllers/HomeController.cs
  SalesAdminPortal/SalesAdminPortal/Views/Home/About.cshtml
Labels: good first issue

#5 changes
  SalesAdminPortal/SalesAdminPortal/Views/Home/Index.cshtml
Labels: duplicate

#27 Implementation of Coupon Generation Algorithm and API Exposure
  SalesAdminPortal/CouponCode.Tests/CouponCode.Tests.csproj
  SalesAdminPortal/CouponCode.Tests/CouponCodeTests.cs
  SalesAdminPortal/CouponCode.Tests/Properties/AssemblyInfo.cs
  SalesAdminPortal/CouponCode.Tests/packages.config
  SalesAdminPortal/CouponCode/CouponCode.csproj
  SalesAdminPortal/CouponCode/CouponCodeBuilder.cs
  SalesAdminPortal/CouponCode/Options.cs
  SalesAdminPortal/CouponCode/Properties/AssemblyInfo.cs
  SalesAdminPortal/CouponCode/SecureRandom.cs
  SalesAdminPortal/SalesAdminPortal.sln
  SalesAdminPortal/SalesAdminPortal/Controllers/CouponController.cs
  SalesAdminPortal/SalesAdminPortal/SalesAdminPortal.csproj
Labels: enhancement

#31 Implementation of the coupon code generation in the UI
  SalesAdminPortal/SalesAdminPortal/Controllers/CouponController.cs
  SalesAdminPortal/SalesAdminPortal/Views/Home/Index.cshtml
  SalesAdminPortal/SalesAdminPortal/Views/Shared/_Layout.cshtml
Labels: test-ui-feature

#32 Undoing Home Controller Code
  SalesAdminPortal/SalesAdminPortal/Controllers/HomeController.cs
Labels: test-ui-feature

#33 URL fixing
  SalesAdminPortal/SalesAdminPortal/Views/Home/Index.cshtml
Labels: test-ui-feature

#34 Implementation of Admin Theme and already implemented functionalities…
  SalesAdminPortal/SalesAdminPortal/App_Start/BundleConfig.cs
  SalesAdminPortal/SalesAdminPortal/Content/Layout/font-awesome.css
  SalesAdminPortal/SalesAdminPortal/Content/Layout/font.css
  SalesAdminPortal/SalesAdminPortal/Content/Layout/jqvmap.css
  SalesAdminPortal/SalesAdminPortal/Content/Layout/lightbox.css
  SalesAdminPortal/SalesAdminPortal/Content/Layout/minimal.css
  SalesAdminPortal/SalesAdminPortal/Content/Layout/monthly.css
  SalesAdminPortal/SalesAdminPortal/Content/Layout/morris.css
  SalesAdminPortal/SalesAdminPortal/Content/Layout/style-responsive.css
  SalesAdminPortal/SalesAdminPortal/Content/Layout/style.css
  SalesAdminPortal/SalesAdminPortal/Controllers/CouponController.cs
  SalesAdminPortal/SalesAdminPortal/Images/bg.jpg
  SalesAdminPortal/SalesAdminPortal/Images/close.png
  SalesAdminPortal/SalesAdminPortal/Images/image1.png
  SalesAdminPortal/SalesAdminPortal/Images/logo.png
  SalesAdminPortal/SalesAdminPortal/Images/mail.png
  SalesAdminPortal/SalesAdminPortal/Images/minimal.png
  SalesAdminPortal/SalesAdminPortal/Images/nav-expand.png
  SalesAdminPortal/SalesAdminPortal/Images/next.png
  SalesAdminPortal/SalesAdminPortal/Images/pass.png
  SalesAdminPortal/SalesAdminPortal/Images/prev.png
  SalesAdminPortal/SalesAdminPortal/Images/search-icon.png
  SalesAdminPortal/SalesAdminPortal/SalesAdminPortal.csproj
  SalesAdminPortal/SalesAdminPortal/Scripts/Layout/bootstrap.js
  SalesAdminPortal/SalesAdminPortal/Scripts/Layout/jquery.dcjqaccordion.2.7.js
  SalesAdminPortal/SalesAdminPortal/Scripts/Layout/jquery.fileupload.js
  SalesAdminPortal/SalesAdminPortal/Scripts/Layout/jquery.nicescroll.js
  SalesAdminPortal/SalesAdminPortal/Scripts/Layout/jquery.scrollTo.js
  SalesAdminPortal/SalesAdminPortal/Scripts/Layout/jquery.slimscroll.js
  SalesAdminPortal/SalesAdminPortal/Scripts/Layout/jquery.vmap.asia.js
  SalesAdminPortal/SalesAdminPortal/Scripts/Layout/jquery.vmap.australia.js
  SalesAdminPortal/SalesAdminPortal/Scripts/Layout/jquery.vmap.europe.js
  SalesAdminPortal/SalesAdminPortal/Scripts/Layout/jquery.vmap.js
  SalesAdminPortal/SalesAdminPortal/Scripts/Layout/jquery.vmap.sampledata.js
  SalesAdminPortal/SalesAdminPortal/Scripts/Layout/jquery.vmap.world.js
  SalesAdminPortal/SalesAdminPortal/Scripts/Layout/jquery2.0.3.min.js
  SalesAdminPortal/SalesAdminPortal/Scripts/Layout/lightbox-plus-jquery.min.js
  SalesAdminPortal/SalesAdminPortal/Scripts/Layout/monthly.js
  SalesAdminPortal/SalesAdminPortal/Scripts/Layout/morris.js
  SalesAdminPortal/SalesAdminPortal/Scripts/Layout/raphael-min.js
  SalesAdminPortal/SalesAdminPortal/Scripts/Layout/script.js
  SalesAdminPortal/SalesAdminPortal/Scripts/Layout/scripts.js
  SalesAdminPortal/SalesAdminPortal/Views/Account/Login.cshtml
  SalesAdminPortal/SalesAdminPortal/Views/Coupon/Create.cshtml
  SalesAdminPortal/SalesAdminPortal/Views/Home/Index.cshtml
  SalesAdminPortal/SalesAdminPortal/Views/Shared/_Layout.cshtml
  SalesAdminPortal/SalesAdminPortal/fonts/FontAwesome.otf
  SalesAdminPortal/SalesAdminPortal/fonts/fontawesome-webfont.eot
  SalesAdminPortal/SalesAdminPortal/fonts/fontawesome-webfont.svg
  SalesAdminPortal/SalesAdminPortal/fonts/fontawesome-webfont.ttf
  SalesAdminPortal/SalesAdminPortal/fonts/fontawesome-webfont.woff
  SalesAdminPortal/SalesAdminPortal/fonts/fontawesome-webfont.woff2
Labels: enhancement

#35 Changes for Agent Code Generation
  SalesAdminPortal/SalesAdminPortal/Controllers/AccountController.cs
  SalesAdminPortal/SalesAdminPortal/Helpers/IdentityExtensions.cs
  SalesAdminPortal/SalesAdminPortal/Models/AccountViewModels.cs
  SalesAdminPortal/SalesAdminPortal/Models/IdentityModels.cs
  SalesAdminPortal/SalesAdminPortal/Views/Account/Register.cshtml
Labels: enhancement

#36 Implementation of user account and agent code and few style fixes
  SalesAdminPortal/SalesAdminPortal/Controllers/AccountController.cs
  SalesAdminPortal/SalesAdminPortal/Helpers/IdentityExtensions.cs
  SalesAdminPortal/SalesAdminPortal/Models/IdentityModels.cs
  SalesAdminPortal/SalesAdminPortal/SalesAdminPortal.csproj
  SalesAdminPortal/SalesAdminPortal/Views/Account/Register.cshtml
  SalesAdminPortal/SalesAdminPortal/Views/Account/Success.cshtml
  SalesAdminPortal/SalesAdminPortal/Views/Shared/_Layout.cshtml
Labels: enhancement

#37 User Management Grid
  SalesAdminPortal/SalesAdminPortal/App_Start/IdentityConfig.cs
  SalesAdminPortal/SalesAdminPortal/Content/ui.jqgrid-bootstrap.css
  SalesAdminPortal/SalesAdminPortal/Controllers/AccountController.cs
  SalesAdminPortal/SalesAdminPortal/Controllers/HomeController.cs
  SalesAdminPortal/SalesAdminPortal/Helpers/IdentityExtensions.cs
  SalesAdminPortal/SalesAdminPortal/Models/AccountViewModels.cs
  SalesAdminPortal/SalesAdminPortal/Models/IdentityModels.cs
  SalesAdminPortal/SalesAdminPortal/SalesAdminPortal.csproj
  SalesAdminPortal/SalesAdminPortal/Scripts/grid.locale-en.js
  SalesAdminPortal/SalesAdminPortal/Scripts/jquery.jqGrid.min.js
  SalesAdminPortal/SalesAdminPortal/Views/Account/ManageUser.cshtml
  SalesAdminPortal/SalesAdminPortal/Views/Account/Register.cshtml
  SalesAdminPortal/SalesAdminPortal/Views/Home/Index.cshtml
  SalesAdminPortal/SalesAdminPortal/Views/Shared/_Layout.cshtml
Labels: enhancement

#38 Implementation of backend for sales trans
  SalesAdminPortal/SalesAdminPortal/Controllers/SalesHandlerController.cs
  SalesAdminPortal/SalesAdminPortal/Models/IdentityModels.cs
  SalesAdminPortal/SalesAdminPortal/Models/ManageViewModels.cs
  SalesAdminPortal/SalesAdminPortal/SalesAdminPortal.csproj
Labels: enhancement

#41 Changes for commission
  SalesAdminPortal/SalesAdminPortal/Controllers/SalesViewController.cs
  SalesAdminPortal/SalesAdminPortal/Views/SalesView/Commission.cshtml
Labels: enhancement

#42 Adding Production Congfig
  SalesAdminPortal/CouponCode/CouponCode.csproj
  SalesAdminPortal/SalesAdminPortal.sln
  SalesAdminPortal/SalesAdminPortal/App_Start/BundleConfig.cs
  SalesAdminPortal/SalesAdminPortal/SalesAdminPortal.csproj
  SalesAdminPortal/SalesAdminPortal/Web.Production.config
Labels: prod config

#43 Changes for NewsFeed andPdf
  SalesAdminPortal/SalesAdminPortal/Controllers/NewsFeedController.cs
  SalesAdminPortal/SalesAdminPortal/Controllers/SalesHandlerController.cs
  SalesAdminPortal/SalesAdminPortal/Models/IdentityModels.cs
  SalesAdminPortal/SalesAdminPortal/SalesAdminPortal.csproj
  SalesAdminPortal/SalesAdminPortal/Views/NewsFeed/Index.cshtml
  SalesAdminPortal/SalesAdminPortal/Views/NewsFeed/ViewFeeds.cshtml
  SalesAdminPortal/SalesAdminPortal/packages.config
Labels: enhancement

#44 Changes for Commission Book Implementation
  SalesAdminPortal/SalesAdminPortal/Views/SalesView/Commission.cshtml
  SalesAdminPortal/SalesAdminPortal/Views/Shared/_Layout.cshtml
Labels: enhancement

#45 Feature/commissionandpdf
  SalesAdminPortal/SalesAdminPortal/App_Start/SwaggerConfig.cs
  SalesAdminPortal/SalesAdminPortal/Controllers/AccountController.cs
  SalesAdminPortal/SalesAdminPortal/Controllers/SalesHandlerController.cs
  SalesAdminPortal/SalesAdminPortal/Controllers/SalesViewController.cs
  SalesAdminPortal/SalesAdminPortal/Global.asax.cs
  SalesAdminPortal/SalesAdminPortal/SalesAdminPortal.csproj
  SalesAdminPortal/SalesAdminPortal/Views/Account/_SuperAdminRegister.cshtml
  SalesAdminPortal/SalesAdminPortal/Views/SalesView/Commission.cshtml
  SalesAdminPortal/SalesAdminPortal/Web.config
  SalesAdminPortal/SalesAdminPortal/packages.config
Labels: enhancement

#46 Adding Dynamic URL
  SalesAdminPortal/SalesAdminPortal/Views/SalesView/Commission.cshtml
  SalesAdminPortal/SalesAdminPortal/Web.Release.config
  SalesAdminPortal/SalesAdminPortal/Web.config
Labels: enhancement

#52 Bug/encode uri fix
  SalesAdminPortal/SalesAdminPortal/Views/SalesView/Commission.cshtml
Labels: enhancement

#57 Changes for PDF generation and date range fix
  SalesAdminPortal/SalesAdminPortal/Controllers/SalesHandlerController.cs
  SalesAdminPortal/SalesAdminPortal/Views/SalesView/Commission.cshtml
  SalesAdminPortal/SalesAdminPortal/Web.Production.config
  SalesAdminPortal/SalesAdminPortal/Web.Release.config
  SalesAdminPortal/SalesAdminPortal/Web.config
Labels: bug

#59 Feature/news
  SalesAdminPortal/SalesAdminPortal/Controllers/SalesHandlerController.cs
  SalesAdminPortal/SalesAdminPortal/Models/IdentityModels.cs
  SalesAdminPortal/SalesAdminPortal/Models/ManageViewModels.cs
  SalesAdminPortal/SalesAdminPortal/Views/SalesView/Commission.cshtml
  SalesAdminPortal/SalesAdminPortal/Web.Release.config
Labels: enhancement

#60 Required UI Changes
  SalesAdminPortal/SalesAdminPortal/Views/SalesView/Commission.cshtml
  SalesAdminPortal/SalesAdminPortal/Web.Release.config
Labels: enhancement
